name: "Pull Request Build"
on:
  - pull_request
jobs:
  linux-build-jvm:
    name: PR - Linux - JVM build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK {{ matrix.java }}
        uses: joschi/setup-jdk@fdc8726d3eaee700a67647704c396f71fe773eed
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Build
        run: |
          mvn -s .github/mvn-settings.xml clean install -Dvalidate-format